### ISSUE TITLE
JSON::ParserError when running any command

### ISSUE THREAD

**Issue by colinsoleim** [PromisePay/promisepay-ruby#42]
I've been using promisepay for a few months and suddenly a week or so ago, I ran into a problem which occurs after running any command. For example, after running these two commands in the rails console,

```
client = Promisepay::Client.new(username: ENV['PROMISEPAY_USERNAME'], token: ENV['PROMISEPAY_TOKEN'])

user = client.users.create(
  id: '123456',
  first_name: 'test',
  last_name: 'buyer',
  email: 'buyer@test.com',
  address_line1: '48 collingwood',
  state: 'vic',
  city: 'Mel',
  zip: '3000',
  country: 'AUS',
  dob:'12/06/1980'
)
```

gives this error and stack trace

```
JSON::ParserError: A JSON text must at least contain two octets!
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/error.rb:43:in `build_error_message'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/error.rb:31:in `initialize'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/error.rb:25:in `new'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/error.rb:25:in `from_response'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/client.rb:180:in `on_complete'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/client.rb:82:in `post'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/resources/user_resource.rb:43:in `create'
	from (irb):50
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
```

I get a similar error when running `items = client.items.find_all`. This is the error and stack trace:
```
JSON::ParserError: A JSON text must at least contain two octets!
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/error.rb:43:in `build_error_message'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/error.rb:31:in `initialize'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/error.rb:25:in `new'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/error.rb:25:in `from_response'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/client.rb:180:in `on_complete'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/client.rb:67:in `get'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/promisepay-1.1.0/lib/promisepay/resources/item_resource.rb:18:in `find_all'
	from (irb):73
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/colinsoleim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
```

Any and all help would be appreciated. Thank you!

**Comment by ngelx** [comment]
Hey there, 

The error seems to be caused in the error response processing. Not sure what is going on there, but you can try to get the [raw error response](https://github.com/PromisePay/promisepay-ruby/issues/25#issuecomment-238961588 ) to get better info. 

Another thing you can try is to use Postman to see what the error is.
